/* security-20261009: real authentication required before protected API access */
(function(){
'use strict';
if(window.__securityAuthInstalled)return;window.__securityAuthInstalled=true;
const nativeFetch=window.fetch.bind(window);
const refs=['vnnvuxccazkdzwqjmntz','emauqxftmauvsffdjvyh'];
const publishable={vnnvuxccazkdzwqjmntz:'sb_publishable_xG-tuBgxFGntT1vlbZzuVQ_AZ2Zl8QL',emauqxftmauvsffdjvyh:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtYXVxeGZ0bWF1dnNmZmRqdnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4Njg0NzksImV4cCI6MjEwMjQ0NDQ3OX0.iN2xz71VCeP7o6nz89v0wJMrUYkGyPKATtWaCl-MIO4"};
const pending=new Map();
function base(ref){return 'https://'+ref+'.supabase.co'}
function read(ref){try{return JSON.parse(localStorage.getItem('sb-'+ref+'-auth-token')||'null')}catch{return null}}
function save(ref,s){if(!s.expires_at)s.expires_at=Math.floor(Date.now()/1000)+Number(s.expires_in||3600);localStorage.setItem('sb-'+ref+'-auth-token',JSON.stringify(s))}
async function auth(ref,path,body){const r=await nativeFetch(base(ref)+'/auth/v1/'+path,{method:'POST',headers:{apikey:publishable[ref],'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||d.message||'認証できませんでした');return d}
async function valid(ref){let s=read(ref);if(!s?.access_token)return null;if(Number(s.expires_at||0)<Date.now()/1000+60){try{s=await auth(ref,'token?grant_type=refresh_token',{refresh_token:s.refresh_token});save(ref,s)}catch{return null}}const r=await nativeFetch(base(ref)+'/auth/v1/user',{headers:{apikey:publishable[ref],Authorization:'Bearer '+s.access_token}});if(!r.ok)return null;const u=await r.json();return u?.id&&u.email_confirmed_at&&!u.is_anonymous?s:null}
function bodyReady(){return document.body?Promise.resolve():new Promise(r=>document.addEventListener('DOMContentLoaded',r,{once:true}))}
async function promptLogin(ref){await bodyReady();return new Promise(resolve=>{const ov=document.createElement('div');ov.id='security-login-'+ref;ov.style.cssText='position:fixed;inset:0;z-index:2147483646;background:#f5f7fa;display:flex;align-items:center;justify-content:center;padding:20px;font-family:system-ui';
ov.innerHTML='<form style="width:min(420px,100%);background:white;padding:24px;border-radius:18px;box-shadow:0 10px 40px #0002"><h2>業務アプリへログイン</h2><p>会社の情報を守るため、本人確認が必要です。</p><label>メールアドレス<input name="email" type="email" required autocomplete="username" style="width:100%;box-sizing:border-box;padding:12px;margin:8px 0;font-size:16px"></label><label>パスワード<input name="password" type="password" required autocomplete="current-password" style="width:100%;box-sizing:border-box;padding:12px;margin:8px 0;font-size:16px"></label><button type="submit" style="width:100%;padding:14px;background:#17212b;color:white;border:0;border-radius:10px;font-size:16px">ログイン</button><button type="button" data-setup style="margin-top:12px;padding:10px">初回パスワード設定</button><p data-msg role="status" style="color:#b91c1c;white-space:pre-wrap"></p></form>';
const form=ov.querySelector('form'),msg=ov.querySelector('[data-msg]'),setup=ov.querySelector('[data-setup]');
form.elements.email.value=ref===refs[0]?'fuucha96@yahoo.co.jp':'yuubae96@gmail.com';setup.hidden=ref!==refs[1];
async function submit(signup){const email=form.elements.email.value.trim(),password=form.elements.password.value;if(signup&&password.length<12){msg.textContent='初回パスワードは12文字以上にしてください';return}form.querySelectorAll('button').forEach(b=>b.disabled=true);msg.textContent='確認中…';try{const s=await auth(ref,signup?'signup':'token?grant_type=password',{email,password});if(!s.access_token){msg.textContent='確認メールを送りました。メールで確認を完了してからログインしてください。';return}save(ref,s);if(!await valid(ref)){msg.textContent='メール確認を完了してからログインしてください';return}ov.remove();resolve(s);setTimeout(()=>location.reload(),0)}catch(e){msg.textContent=e.message}finally{form.querySelectorAll('button').forEach(b=>b.disabled=false)}}
form.onsubmit=e=>{e.preventDefault();submit(false)};setup.onclick=()=>submit(true);document.body.appendChild(ov);})}
async function session(ref){if(pending.has(ref))return pending.get(ref);const p=(async()=>await valid(ref)||await promptLogin(ref))();pending.set(ref,p);try{return await p}finally{pending.delete(ref)}}
window.securityRequireSession=session;

const signedCache=new Map();
async function signedUrl(url){const u=new URL(url),ref=refs.find(r=>u.hostname===r+'.supabase.co');if(!ref||!u.pathname.startsWith('/storage/v1/object/public/'))return url;const cached=signedCache.get(url);if(cached&&cached.until>Date.now())return cached.url;const s=await session(ref),path=u.pathname.replace('/storage/v1/object/public/','');const r=await nativeFetch(base(ref)+'/storage/v1/object/sign/'+path,{method:'POST',headers:{apikey:publishable[ref],Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:300})});const d=await r.json();if(!r.ok||!d.signedURL)throw Error('ファイルを開く権限がありません');const result=d.signedURL.startsWith('http')?d.signedURL:base(ref)+'/storage/v1'+d.signedURL;signedCache.set(url,{url:result,until:Date.now()+120000});return result}
async function protectJson(value){if(typeof value==='string'&&/^https:\/\/[^/]+\.supabase\.co\/storage\/v1\/object\/public\//.test(value))return signedUrl(value);if(Array.isArray(value))return Promise.all(value.map(protectJson));if(value&&typeof value==='object'){const out={};for(const [k,v] of Object.entries(value))out[k]=await protectJson(v);return out}return value}
async function protectImage(img){if(img.dataset.securitySigning||!img.src?.includes('.supabase.co/storage/v1/object/public/'))return;img.dataset.securitySigning='1';try{img.src=await signedUrl(img.src)}catch{img.alt='ログイン後に表示されます'}finally{delete img.dataset.securitySigning}}
bodyReady().then(()=>{document.querySelectorAll('img').forEach(protectImage);new MutationObserver(records=>{for(const r of records){if(r.type==='attributes'&&r.target.tagName==='IMG')protectImage(r.target);for(const n of r.addedNodes||[])if(n.nodeType===1){if(n.tagName==='IMG')protectImage(n);n.querySelectorAll?.('img').forEach(protectImage)}}}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['src']});document.addEventListener('click',async e=>{const a=e.target.closest?.('a[href]');if(!a?.href.includes('.supabase.co/storage/v1/object/public/'))return;e.preventDefault();const win=window.open('about:blank','_blank');try{const url=await signedUrl(a.href);if(win)win.location.href=url;else location.href=url}catch(err){win?.close();alert(err.message)}});});

window.fetch=async function(input,init){const request=new Request(input,init);const u=new URL(request.url);const ref=refs.find(r=>u.hostname===r+'.supabase.co');if(!ref||!/^\/(rest|functions|storage)\/v1\//.test(u.pathname))return nativeFetch(input,init);const s=await session(ref),headers=new Headers(request.headers);headers.set('apikey',publishable[ref]);headers.set('Authorization','Bearer '+s.access_token);
if(u.pathname.startsWith('/storage/v1/object/public/'))u.pathname=u.pathname.replace('/object/public/','/object/authenticated/');
let payload;if(!['GET','HEAD'].includes(request.method)){if(u.pathname.startsWith('/functions/v1/')&&(request.headers.get('content-type')||'').includes('application/json')){const text=await request.text();payload=text.includes('/storage/v1/object/public/')?JSON.stringify(await protectJson(JSON.parse(text))):text}else payload=await request.blob()}
return nativeFetch(new Request(u.href,{method:request.method,headers,body:payload,signal:request.signal,credentials:request.credentials,cache:request.cache}));};
const defaultRef=document.currentScript?.dataset.project||refs[0];
session(defaultRef).catch(()=>{});
})();